### ISSUE TITLE
How to generate the test result vedio?

### ISSUE THREAD

**Issue by Evens1sen** [nrsyed/svm-vehicle-detector#4]
I clone your code and run it to get the expected output in the terminal, but I can't get the result vedio as expected. My running enviroment is the Windows10 with Python 3.9.

**Comment by nrsyed** [comment]
@Evens1sen I think I used a modified version of the code to produce the test video(s). I'll have to dig through some of my old files to see what those modifications were, and may update this repo accordingly.
